Allow applications and scripts to be launched within the sessions
openflighthpc/flight-desktop pull request #36
Opened 2021-07-07 18:08 UTC by WilliamMcCumstie

A new `--script` and `--app` flags have been added to launch `scripts` and `applications` within the sessions. `scripts` are intended to be launched within a new terminal, where applications are launched directly. In ever case the `DISPLAY` variable is set, so both flags accept scripts.

Due to the idiosyncrasies in the various session `types`, the two flags shell out to `launch-script` and `launch-app` shims respectively. This allows session type specific setup and a way to disable the flags per type.

Multiple apps can be launched be repeating the `--app` flag (similarly for `--script`). This required upgrading `commander` to version `2.2`

2021-07-15 16:20 UTC, benarmston requested changes
This works well for both `gnome` and `xfce`, but I think both `terminal` and `xterm` need some work.

The problem with using `screen` is that its session hangs around after the desktop session has terminated and potentially after the interactive job has timedout.  We don't want to rely on users cleaning up after themselves.

Another issue with using `screen` is that the user still needs to connect to the screen session after the VNC session has started.  It would be a much nicer experience if they were immediately presented with the programs they have launched.  This could be achieved by having the `terminal/session.sh` script run the script it is given. 

This would result in terminal sessions only supporting a single script, but in practice that is all that they are going to need.

2021-07-20 15:34 UTC, WilliamMcCumstie commented on lib/desktop/cli.rb
> +        Not supported by all desktop types.
Updated

2021-07-20 15:35 UTC, WilliamMcCumstie commented on lib/desktop/cli.rb
> +        Not supported by all desktop types.
Updated

2021-07-20 15:41 UTC, WilliamMcCumstie commented
The launching of scripts for `xterm` and `terminal` has been reworked. There are now three mechanisms to launch app/scripts:

1. The `--app` will call `launch-app.sh` to create graphical applications,
2. The `--script` will attempt to call `launch-script.sh` to create a graphical terminal, OR
3. `--script` will fallback on patching the `session.sh` to start a single script.

Options 1/2 are the same as above and are used by `xfce` and `gnome`. The `--app` and `--script` flags can be repeated to launch multiple applications.

However `xterm` and `terminal` now flag that they are `scriptable` within their metadata. This denotes they can run a script via their `session.sh`.

Because `flight-desktop` is built on `vncserver`, it can only specify a single `-sessionscript`. This means the `session.sh` must contain the desktop specific start code as well as the script command. This has been achieved by patching the `script` into `session.sh` when it is "installed".

2021-08-05 11:55 UTC, benarmston commented
Rebeased on `master`.

2021-08-05 15:20 UTC, merged