CLI argument for persisting environment
openflighthpc/flight-desktop pull request #40
Opened 2021-11-02 10:38 UTC by VoxSecundus

This PR introduces a new command line option to `flight desktop start` which disables the regular behaviour of blanking the session environment and allows the environment variables of the host machine to persist. The option, `--no-env-override`, has simply been added to the logic used when deciding whether to reset the session environment.

Appropriate documentation has been added to `openflight-omnibus-builder` to describe this new argument.

2021-11-02 17:24 UTC, benarmston requested changes
This looks to be about right.  I've left a couple of picky comments about some lines having incorrect indentation.  Please take a look at those.

Also for symmetry it would be nice to have an option to force environment overriding.  That is an `--env-override` option. Although perhaps they would be better named `--override-env` and `--no-override-env`.  I'm assuming that it will be quite quick to add that second option.  If it is please do so.

2021-11-02 17:24 UTC, benarmston commented on lib/desktop/commands/start.rb
> +	      no_env_override: @options.no_env_override
The indentation looks wrong here.

2021-11-02 17:24 UTC, benarmston commented on lib/desktop/session.rb
> +	  ).tap do |started|
The indentation looks wrong here too.

2021-11-02 17:35 UTC, VoxSecundus commented
Those indentation mishaps were down to my `.vimrc` settings, and were invisible in my editor. I've changed my settings to match the existing indentation flavour.

2021-11-04 14:13 UTC, benarmston requested changes
Can I get you to look at another picky change please?

2021-11-04 14:13 UTC, benarmston commented on lib/desktop/session.rb
> +      env_override = override_env || !no_override_env && Config.session_env_override
Would this not be better located `commands/start.rb`? That way only a single authoritative option would be need to be passed through the various `session.rb` calls.

2021-11-04 17:20 UTC, benarmston commented
LGTM.  Thanks @VoxSecundus

2021-11-04 17:21 UTC, merged